// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQFD8Fm7QZaHeS4HO11quRy7ZELUYo-Uo',
    appId: '1:562612444725:web:cd68ceedf1208203649b7c',
    messagingSenderId: '562612444725',
    projectId: 'batalhaideias',
    authDomain: 'batalhaideias.firebaseapp.com',
    storageBucket: 'batalhaideias.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFTu02iQI5QXmdVpuUmCAQV8I3BBcI6nI',
    appId: '1:562612444725:android:41b833e4f13fc6f5649b7c',
    messagingSenderId: '562612444725',
    projectId: 'batalhaideias',
    storageBucket: 'batalhaideias.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlegcF1RoS8oeErb4dhLlRTCJwii-JkNE',
    appId: '1:562612444725:ios:aab744621f407799649b7c',
    messagingSenderId: '562612444725',
    projectId: 'batalhaideias',
    storageBucket: 'batalhaideias.firebasestorage.app',
    iosBundleId: 'com.example.batalhaIdeias',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlegcF1RoS8oeErb4dhLlRTCJwii-JkNE',
    appId: '1:562612444725:ios:aab744621f407799649b7c',
    messagingSenderId: '562612444725',
    projectId: 'batalhaideias',
    storageBucket: 'batalhaideias.firebasestorage.app',
    iosBundleId: 'com.example.batalhaIdeias',
  );
}
