// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjf0dpC-E_oanzbJO6JwfDM2ZUOriCfts',
    appId: '1:724823018036:web:bb1de498cd652e2414d861',
    messagingSenderId: '724823018036',
    projectId: 'projeto1-81939',
    authDomain: 'projeto1-81939.firebaseapp.com',
    storageBucket: 'projeto1-81939.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqwlxmpic5XREyb_7aBlTzDfVsoY-AKQo',
    appId: '1:724823018036:android:ae51844dd0008ef914d861',
    messagingSenderId: '724823018036',
    projectId: 'projeto1-81939',
    storageBucket: 'projeto1-81939.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdLplPknQomlCFG5gNKIYN3rVxZ4950w4',
    appId: '1:724823018036:ios:190b6ca431c4e34614d861',
    messagingSenderId: '724823018036',
    projectId: 'projeto1-81939',
    storageBucket: 'projeto1-81939.firebasestorage.app',
    iosBundleId: 'com.example.fireFlutter',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdLplPknQomlCFG5gNKIYN3rVxZ4950w4',
    appId: '1:724823018036:ios:190b6ca431c4e34614d861',
    messagingSenderId: '724823018036',
    projectId: 'projeto1-81939',
    storageBucket: 'projeto1-81939.firebasestorage.app',
    iosBundleId: 'com.example.fireFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjf0dpC-E_oanzbJO6JwfDM2ZUOriCfts',
    appId: '1:724823018036:web:35a318fa8c478a1014d861',
    messagingSenderId: '724823018036',
    projectId: 'projeto1-81939',
    authDomain: 'projeto1-81939.firebaseapp.com',
    storageBucket: 'projeto1-81939.firebasestorage.app',
  );
}
