// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCt_Mp2wY3Qyjkker159wKRRbW2ZPT0FeU',
    appId: '1:754943240334:web:687fbb14da75a1a0f6c1df',
    messagingSenderId: '754943240334',
    projectId: 'authfire-bb03d',
    authDomain: 'authfire-bb03d.firebaseapp.com',
    storageBucket: 'authfire-bb03d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVcprR8mtlh7maSXcFcXro0riMMHTqXas',
    appId: '1:754943240334:android:ad7e6ccb7e8597d9f6c1df',
    messagingSenderId: '754943240334',
    projectId: 'authfire-bb03d',
    storageBucket: 'authfire-bb03d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnyr0-h1tXKnswmHMbwjsRQeKks4zRUc8',
    appId: '1:754943240334:ios:0539670f219dc4b3f6c1df',
    messagingSenderId: '754943240334',
    projectId: 'authfire-bb03d',
    storageBucket: 'authfire-bb03d.firebasestorage.app',
    iosClientId: '754943240334-ch5gok7vlkgneit2q54rk1tvaqmpgvk0.apps.googleusercontent.com',
    iosBundleId: 'com.example.fireFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnyr0-h1tXKnswmHMbwjsRQeKks4zRUc8',
    appId: '1:754943240334:ios:0539670f219dc4b3f6c1df',
    messagingSenderId: '754943240334',
    projectId: 'authfire-bb03d',
    storageBucket: 'authfire-bb03d.firebasestorage.app',
    iosClientId: '754943240334-ch5gok7vlkgneit2q54rk1tvaqmpgvk0.apps.googleusercontent.com',
    iosBundleId: 'com.example.fireFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCt_Mp2wY3Qyjkker159wKRRbW2ZPT0FeU',
    appId: '1:754943240334:web:a0209a56e5a8c749f6c1df',
    messagingSenderId: '754943240334',
    projectId: 'authfire-bb03d',
    authDomain: 'authfire-bb03d.firebaseapp.com',
    storageBucket: 'authfire-bb03d.firebasestorage.app',
  );
}
