// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClZtCnhKtjHf_4YEfRkLJwFgTVpf44Zbk',
    appId: '1:490081542396:web:a5bde47d46efb666a57779',
    messagingSenderId: '490081542396',
    projectId: 'centralmissoes-f0580',
    authDomain: 'centralmissoes-f0580.firebaseapp.com',
    storageBucket: 'centralmissoes-f0580.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPW4TAogpUXpSDTp_bPP8_lgJVKhZztLA',
    appId: '1:490081542396:android:e7e2d2539232ce1aa57779',
    messagingSenderId: '490081542396',
    projectId: 'centralmissoes-f0580',
    storageBucket: 'centralmissoes-f0580.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhZ-nnYjsAUYduMx8tB_Y4hfrX_lzdt6s',
    appId: '1:490081542396:ios:aeb9c1a33a0ef7bfa57779',
    messagingSenderId: '490081542396',
    projectId: 'centralmissoes-f0580',
    storageBucket: 'centralmissoes-f0580.firebasestorage.app',
    iosBundleId: 'com.example.centralMissoesFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhZ-nnYjsAUYduMx8tB_Y4hfrX_lzdt6s',
    appId: '1:490081542396:ios:aeb9c1a33a0ef7bfa57779',
    messagingSenderId: '490081542396',
    projectId: 'centralmissoes-f0580',
    storageBucket: 'centralmissoes-f0580.firebasestorage.app',
    iosBundleId: 'com.example.centralMissoesFirebase',
  );
}
